# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=leyline
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_DB=leyline
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: leyline
      POSTGRES_PASSWORD: password
      POSTGRES_DB: leyline
    ports:
      - "5433:5432"