apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-rest-api.name" . }}
  labels:
    app: {{ include "my-rest-api.name" . }}
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: {{ include "my-rest-api.name" . }}
